SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20  # radius of the player's ship
LINE_WIDTH = 2  # width of the lines drawn the player's ship
PLAYER_TURN_SPEED = 300 # degrees per second the player can turn
PLAYER_SPEED = 200 # pixels per second the player moves forward
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3  # seconds between shots